# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(max_length=30)),
                ('eventID', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
