# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendz', '0004_auto_20160418_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='occurances',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.IntegerField(),
        ),
    ]
