# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendz', '0005_auto_20160418_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='occurances',
            field=models.IntegerField(default=0),
        ),
    ]
