# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendz', '0007_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
