# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendz', '0008_auto_20160418_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
